services:
  db:
    restart: always
    image: mysql:8.0
    platform: linux/arm64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'

  mysql-client:
    image: mysql:8.0
    platform: linux/arm64
    command: bash -c "sleep infinity"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
  web:
    build: .
    working_dir: /core
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - ./core:/core
      - gemdata:/usr/local/bundle
      - node_modules:/core/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
volumes:
  gemdata:
  node_modules:
  mysqldata:
